# Generated by Django 3.2.9 on 2021-11-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
